name = "FranklinTemplates"
uuid = "3a985190-f512-4703-8d38-2a7944ed5916"
authors = ["Thibaut Lienart <tlienart@me.com>"]
version = "0.10.3"

[deps]
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"

[compat]
LiveServer = "1"
julia = "1"
